server:
  port:  2001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username : root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
